export const titleListLocalMap = {
  billCode: {
    id: 1,
    title: '是',
    dataIndex: 'billCode',
    width: 300,
    checked: true,
  },
  traceLast: {
    id: 2,
    checked: true,
    title: '追',
    dataIndex: 'traceLast',
    width: 250,
  },
  demandDescription: {
    id: 3,
    checked: true,
    title: '逐',
    dataIndex: 'demandDescription',
    width: 250,
  },
  demandTicketTypeStr: {
    id: 4,
    checked: true,
    title: '梦',
    dataIndex: 'demandTicketTypeStr',
    width: 200,
  },
  merchantName: {
    id: 5,
    checked: true,
    title: '想',
    dataIndex: 'merchantName',
    width: 150,
  },
  statusStr: {
    id: 6,
    checked: true,
    title: '的',
    dataIndex: 'statusStr',
    width: 150,
  },
  createTime: {
    id: 7,
    checked: true,
    title: '二',
    dataIndex: 'createTime',
    width: 150,
  },
  modifiedTime: {
    id: 8,
    checked: true,
    title: '狗',
    dataIndex: 'modifiedTime',
    width: 150,
  },
  customerStaffName: {
    id: 9,
    checked: true,
    title: '子',
    dataIndex: 'customerStaffName',
    width: 150,
  },
};
export const titleListLocal = [
  'billCode',
  'traceLast',
  'demandDescription',
  'demandTicketTypeStr',
  'merchantName',
  'statusStr',
  'createTime',
  'modifiedTime',
  'customerStaffName',
];
